/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dao.NhanVienDAO;
import entities.NhanVien;

import java.util.ArrayList;

import utils.DialogHelper;

/**
 * @author NGUYEN THI NGUYET VY
 */
public class DoiMKForm extends javax.swing.JPanel {
    /**
     * Creates new form FormTemplate
     */
    public DoiMKForm() {
        initComponents();
        txtUser.setText(utils.Auth.user.getMaNhanVien());
    }

    private boolean checkForm() {
        if (String.valueOf(txtConfirmPass.getPassword()).trim().isEmpty()
                || String.valueOf(txtNewPass.getPassword()).trim().isEmpty()) {
            DialogHelper.alert(this, "Vui lòng nhập đầy đủ thông tin!");
            return false;
        }

        if (!String.valueOf(txtConfirmPass.getPassword()).equals(String.valueOf(txtNewPass.getPassword()))) {
            DialogHelper.alert(this, "Mật khẩu mới không trùng khớp!");
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new swing.PanelBorder();
        btnDoiMK = new javax.swing.JButton();
        txtUser = new swing.TextFieldSuggestion();
        txtNewPass = new swing.PasswordField();
        txtConfirmPass = new swing.PasswordField();

        setOpaque(false);

        panelBorder1.setBackground(new java.awt.Color(229, 229, 229));

        btnDoiMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDoiMK.setForeground(new java.awt.Color(32, 136, 203));
        btnDoiMK.setText("Đổi Mật Khẩu");
        btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMKActionPerformed(evt);
            }
        });

        txtUser.setText("Mã Nhân Viên");
        txtUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtNewPass.setLabelText("Mật khẩu mới");

        txtConfirmPass.setLabelText("Xác nhận mật khẩu");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
                panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBorder1Layout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelBorder1Layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                                        .addComponent(txtNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtConfirmPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(309, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
                panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(323, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMKActionPerformed
        // TODO add your handling code here:
        //                NhanVien nv = new NhanVienDAO().selectById(txtUser.getText());
        //                nv.setMatKhau(String.valueOf(number));
        //                new NhanVienDAO().update(nv);
        if (checkForm()) {
            NhanVien nv = utils.Auth.user;
            nv.setMatKhau(String.valueOf(txtNewPass.getPassword()));
            new NhanVienDAO().update(nv);
            utils.DialogHelper.alert(this, "Cập nhật mật khẩu mới thành công!");
        }
    }//GEN-LAST:event_btnDoiMKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMK;
    private swing.PanelBorder panelBorder1;
    private swing.PasswordField txtConfirmPass;
    private swing.PasswordField txtNewPass;
    private swing.TextFieldSuggestion txtUser;
    // End of variables declaration//GEN-END:variables
}
